Walkthrough notebook (and Embeddings script)
UtrechtUniversity/patent-breakthrough pull request #75
Opened 2023-12-04 13:29 UTC by maartenschermer

Walkthrough notebook + sample data files.
Accidentally tagged onto another branch (`embeddings-script`), hopefully not an issue!

2023-12-04 13:59 UTC, qubixes requested changes
Looks really great, thanks! Just some minor questions from my side.

2023-12-04 13:59 UTC, qubixes commented on examples/data/GPCPCs.txt
Did you check with Benjamin if it's okay to share these files?

They are reasonably big (by git standards), maybe it makes sense to sample them?

2023-12-04 13:59 UTC, qubixes commented on examples/walkthrough.ipynb
Looks like a really nice and complete walkthrough, thanks! Would it be possible to make some of the cells markdown to add some captions/section to the file?

2023-12-05 09:09 UTC, ShNadi reviewed
Nice and clear walkthrough, thanks!
Does it make sense to include greek, stopwords, and symbol files for the preprocessing in the data folder?

2023-12-05 10:24 UTC, maartenschermer commented
@ShNadi I don't think we actually use them in the final version.
Nb, I've asked Benjamin about the other files, and he thinks it's a good idea, but he wants to check with his supervisor.

2023-12-05 11:58 UTC, qubixes commented on examples/walkthrough.ipynb
Okay, if it is a big problem, don't worry too much about it. If I can help with anything, let me know.

2023-12-05 12:01 UTC, qubixes commented
> @ShNadi I don't think we actually use them in the final version. Nb, I've asked Benjamin about the other files, and he thinks it's a good idea, but he wants to check with his supervisor.

Aren't they used in the `OldPreprocessor` class? At least as far as I can tell they are used, but I could be wrong.

2023-12-05 13:54 UTC, maartenschermer commented
> Aren't they used in the `OldPreprocessor` class? At least as far as I can tell they are used, but I could be wrong.

That's true, but `OldPreprocessor` is only used in the hyperopt tuning, so maybe we should put the stopword and symbol files there?

2023-12-05 14:28 UTC, qubixes commented
> > Aren't they used in the `OldPreprocessor` class? At least as far as I can tell they are used, but I could be wrong.
> 
> That's true, but `OldPreprocessor` is only used in the hyperopt tuning, so maybe we should put the stopword and symbol files there?

Well, the best results are with the OldPreprocessor according to the hyperopt notebook. @ShNadi is now trying to do the run with the old preprocessor..

2023-12-06 10:40 UTC, maartenschermer commented
Also, Benjamin talked to his supervisor, and they are ok with the sample data files.

2023-12-06 10:44 UTC, qubixes commented
Looks great. Just a minor point: The tf-idf model should use the new preprocessor, not the old one. It's only the CountVec model that uses the old preprocessing method.

2023-12-06 13:53 UTC, qubixes commented
> Ah, ok, I thought I also saw better values with the old one for the Tf-Idf.

I checked now, and you're indeed right. Given that we have run it with  the new preprocessor, might be better to just keep it like that. The difference is well within error margins anyway (not so much for the countvec model!).

2023-12-06 16:43 UTC, merged